### PR TITLE
fix: fixed branch selector

### LINKED ISSUE #331: Selected branch-name in selector and refreshing, removes the chips of the selected branch-names
### Steps to reproduce:

1. Go to /dora-metrics
2. add a custom branch name `^main`
3. refresh this page
4. open branch-selector again
5. branch-chips disappear and you cannot unselect particular branch names

### Expected behavior:

- branch names should render as removable-chips

### Actual behavior:

- no rendered values that can be de-selected

### Server Setup Information:

- Operating System: 
- Deployment Method: 

### Additional context

https://github.com/middlewarehq/middleware/assets/76566992/379b04c5-a88b-4a0e-82ca-07c3c77411a2

### PR DESCRIPTION
**Pull request by ayush3160**
Branch names now are rendering as removable-chips after reloading page.
## Linked Issue(s) 
fixes #331 

## Proposed changes (including videos or screenshots)
https://github.com/middlewarehq/middleware/assets/89914602/2e532a78-33f4-4e84-a49a-6337023a1a48

### CODE REVIEW

**Comment by jayantbh** [comment]
Thanks for both of your PRs, @ayush3160 
Someone from the team will check it out asap.

**Comment by ayush3160** [comment]
Hi @e-for-eshaan , Thanks for reviewing I missed the case of prod and all branches mode but I have fixed it in above commit please have a look and let me know if any other changes are needed.

File: web-server/src/components/BranchSelector.tsx [hunk 1]
```diff
@@ -252,14 +254,15 @@ export const BranchSelector: FC = () => {
...
+              onSelect={() => {
                 dispatch(
                   appSlice.actions.setBranchState({
                     mode: ActiveBranchMode.ALL,
                     names: ''
                   })
-                )
-              }
+                );
+                depFn(localBranchNames.set, []);
```
Comment (e-for-eshaan) [inline web-server/src/components/BranchSelector.tsx:264]: `localBranchNames.set` should be included in the dependency array of the `setProdStateBranchNames` callback

**Review by e-for-eshaan — DISMISSED** [review]

**Comment by e-for-eshaan** [comment]
Hey @ayush3160 ! Sorry for the late response, but your PR looks promising, just tested it locally.
Mentioned a minor change, can be merged right after this!

**Comment by ayush3160** [comment]
Thanks for reviewing @e-for-eshaan , I have done the changes please check once.

**Review by e-for-eshaan — APPROVED** [review]
LGTM! approving this
