### PR TITLE
fix: added a prerequisite check to ensure certain conditions are fulfilled before running docker compose build and watch

### LINKED ISSUE #338: Add pre-requisite checks for the CLI tool
### Description:
Before running the `docker-compose watch` command to set up the development environment, we should add some pre-requisite checks to ensure that the necessary components are available and the required files exist. This will help catch potential issues early and provide a better user experience.

### Pre-requisite Checks:
- [ ] Check if the required ports are available (list the specific ports needed)
- [ ] Check if the Docker daemon is running
- [ ] Check if the `docker-compose.yml` file exists in the project directory
- [ ] Check if the `Dockerfile.dev` exists in the project directory

### Implementation Steps:
1. Identify the required ports for the development environment and add a check to ensure they are not already in use.
2. Add a check to verify if the Docker daemon is running on the system.
3. Add a check to ensure that the `docker-compose.yml` file exists in the project directory.
4. Add a check to ensure that the `Dockerfile.dev` exists in the project directory.
5. Display appropriate error messages or prompts if any of the pre-requisite checks fail.
6. Proceed with the `docker-compose watch` command only if all pre-requisite checks pass.

### Additional Considerations:
- Handle different operating systems (e.g., Linux, macOS, Windows) for checking the Docker daemon status.
- Provide clear instructions or guidance if any of the pre-requisite checks fail, such as suggesting solutions or troubleshooting steps.
- Consider adding unit tests for the pre-requisite check functions.

### PR DESCRIPTION
**Pull request by sidtohan**
## Linked Issue(s) 

fixes #338

## Acceptance Criteria fulfillment

- [x] Check if the required ports are available (list the specific ports needed)
- [x] Check if the Docker daemon is running
- [x] Check if the docker-compose.yml file exists in the project directory
- [x] Check if the Dockerfile.dev exists in the project directory
- [x] Add suggestions or solutions for each error
- [x] Update UI to display errors properly
- [x] Check if the docker version is the correct version which supports `docker compose watch`
- [ ] Add unit tests

## Proposed changes (including videos or screenshots)
- Created a custom hook that checks if docker daemon is running, if the required ports are free, if docker-compose.yml file exists and dockerfile.dev exists.
- Created a basic UI that lists down all the checks when they are running, and if any of them fails, it terminates the process
image

- Added a custom app state called `PREREQ_CHECK`,  which denotes that the app is currently checking the prerequisites. Also, the initial state of the app is now `PREREQ_CHECK` instead of `INIT`.
- Added a new enum in `cli/source/constants.ts` called `PreCheckStates` consisting of three values: `RUNNING, SUCCESS` and `FAILED`. 

## Further comments

There are currently a lot of major changes regarding the dependency arrays for the `useEffect` and the `useCallback` hooks. I have currently implemented them as per my opinion, but I would appreciate some guidance on how we can make it look more cleaner and better.

There is currently a lot of work to be done on the UI as well, but I would first like to get some feedback on the type of approach I've taken. Thanks.

### CODE REVIEW

**Comment by jayantbh** [comment]
Great suggestion, @sidtohan!
Thanks for your PR. We'll look into this.

**Comment by jayantbh** [comment]
Btw, did you run `npm install` by any chance?
Because `cli/package-lock.json` should not be a new file. You'll see there should be a `yarn.lock` indicating that it should use `yarn` as the package manager.

As a result, your PR blew to 7.6k lines. :)

**Review by jayantbh — CHANGES_REQUESTED** [review]
This is an incomplete review. A more thorough review would be done by someone else from the team.

**Comment by jayantbh** [comment]
Hey @sidtohan, are you taking care of the package-lock.json thing?

File: cli/source/app.tsx [hunk 1]
```diff
@@ -149,27 +162,57 @@ const CliUi = () => {
...
+    ) {
+      if (
+        preCheck.daemon === PreCheckStates.FAILED ||
+        preCheck.ports === PreCheckStates.FAILED ||
+        preCheck.composeFile === PreCheckStates.FAILED ||
+        preCheck.dockerFile === PreCheckStates.FAILED
+      )
+        handleExit();
+      return;
+    }
```
[the remark this answers is not in the document]
Comment (sidtohan) [reply cli/source/app.tsx:179]: Actually what I've tried to do here is that if any of the checks is in failed state, then I need to quit the program.
But if any of checks is currently in progress ( essentially the `PreCheckStates.RUNNING` state), then I want to return from here but not exit the program. But you are right, it is quite poorely written. I'll try to simplify it further.

**Comment by sidtohan** [comment]
> Hey @sidtohan, are you taking care of the package-lock.json thing?

Yes, I'm working on it, sorry for the extremely slow response.

**Comment by sidtohan** [comment]
> image
> 
> Your yarn.lock changes would need to be reset as well. It looks like you changed the registry URLs.
> 
> @sidtohan

Sure I'll reset them.

**Comment by sidtohan** [comment]
So I've added the requested changes, regarding the check for the states of the precheck objects, I would greatly appreciate any inputs on how to improve further. 

I've removed the package-lock file and added the installation of the module "find-free-ports" which I'm using in the yarn.lock file. Please let me know if there is any issue regarding that.

Kindly review this whenever convenient. I'll try to be more responsive next week.

File: cli/source/app.tsx [hunk 2]
```diff
@@ -264,12 +299,37 @@ const CliUi = () => {
...
     () => logsStream.map((l) => transformLogToNode(l)),
     [logsStream]
   );
+
+  const PreCheckDisplayElement = ({
+    value,
+    property
+  }: {
+    value: PreCheckStates;
+    property: string;
```
Comment (shivam-bit) [inline cli/source/app.tsx:318]: @sidtohan can you declare type for `property`

**Comment by samad-yar-khan** [comment]
@sidtohan Great PR! Although ports are blocked and daemon is also closed. Its only showing that ports are not accessible and nothing about the daemon. only showing one issue at a time.
image

image

File: cli/source/hooks/usePreCheck.ts [hunk 3]
```diff
@@ -0,0 +1,80 @@
...
+      isNaN(sync_server) ||
+      isNaN(analytics_server)
+    ) {
+      setPorts(PreCheckStates.FAILED);
+    } else {
+      const db_check = await isFreePort(db);
+      const redis_check = await isFreePort(redis);
+      const fe_check = await isFreePort(frontend);
+      const ss_check = await isFreePort(sync_server);
+      const as_check = await isFreePort(analytics_server);
```
Comment (samad-yar-khan) [inline cli/source/hooks/usePreCheck.ts:55]: variable names are ambiguous

**Review by samad-yar-khan — CHANGES_REQUESTED** [review]

File: cli/source/hooks/usePreCheck.ts [hunk 4]
```diff
@@ -0,0 +1,80 @@
...
+      })
+      .catch((err) => {
+        setComposeFile(PreCheckStates.FAILED);
+      });
+
+    fs.promises
+      .access('../Dockerfile.dev')
+      .then(() => setDockerFile(PreCheckStates.SUCCESS))
+      .catch(() => setDockerFile(PreCheckStates.FAILED));
+  };
```
Comment (shivam-bit) [inline cli/source/hooks/usePreCheck.ts:77]: I think you should divide this `callChecks` into 3 smaller callbacks
also prefer to enclose those functions into `useCallback`.

**Review by shivam-bit — CHANGES_REQUESTED** [review]

File: cli/source/hooks/usePreCheck.ts [hunk 5]
```diff
@@ -0,0 +1,80 @@
...
+      const redis_check = await isFreePort(redis);
+      const fe_check = await isFreePort(frontend);
+      const ss_check = await isFreePort(sync_server);
+      const as_check = await isFreePort(analytics_server);
+      if (!db_check || !redis_check || !fe_check || !ss_check || !as_check) {
+        setPorts(PreCheckStates.FAILED);
+      } else {
+        setPorts(PreCheckStates.SUCCESS);
+      }
+    }
```
Comment (adnanhashmi09) [inline cli/source/hooks/usePreCheck.ts:61]: You can use `Promise.all()` and `Promise.allSettled()` to avoid having to store values of promises in variables and conditionally checking them. It might make code more readable, imo. Just a suggestion!

**Review by adnanhashmi09 — CHANGES_REQUESTED** [review]

File: cli/source/app.tsx (hunk 2 above)
Comment (sidtohan) [reply cli/source/app.tsx:318]: Sure, I'll add an enum for this.

File: cli/source/app.tsx [hunk 6]
```diff
@@ -264,12 +299,37 @@ const CliUi = () => {
...
+  }) => {
+    return (
+      <Text>
+        {value === PreCheckStates.RUNNING ? (
+          <Spinner type="dots" />
+        ) : value === PreCheckStates.SUCCESS ? (
+          <Text color="green">✓</Text>
+        ) : (
+          <Text color="red">x</Text>
+        )}{' '}
```
[the remark this answers is not in the document]
Comment (sidtohan) [reply cli/source/app.tsx]: I added this for some space after the tick and cross. If there is some other better way for this please let me know.

File: cli/source/hooks/usePreCheck.ts (hunk 5 above)
Comment (sidtohan) [reply cli/source/hooks/usePreCheck.ts]: So here what would be the better option between `Promise.all()` and `Promise.allSettled()`? If we want better display of failed checks, then it might be better to also display the exact port where it fails (unlike what is being done in the current UI that I implemented). Would the `Promise.allSettled()` be better in that case as it would run all the checks even if one of them fails?

Comment (jayantbh) [reply cli/source/hooks/usePreCheck.ts]: Definitely allSettled.
I don't know about readability, but it'll def be faster.

My suggestion:

```js
const portPromises = [db, redis, frontend, sync_server, analytics_server].map(isFreePort);
const checks = await Promise.allSettled(portPromises);
if (checks.includes(false)) failed;
else passed;
```

**Review by jayantbh — DISMISSED** [review]

**Comment by shivam-bit** [comment]
LGTM
@adnanhashmi09  please check if your requested changed were address or not

**Review by adnanhashmi09 — DISMISSED** [review]

**Comment by adnanhashmi09** [comment]
@sidtohan could you also add this check
- [ ] Check if the docker version is the correct version which supports docker compose watch

It was added in the PR description as well

**Review by shivam-bit — DISMISSED** [review]

**Comment by samad-yar-khan** [comment]
Hey @sidtohan, the port checking logic is buggy. If you block one of your ports, you will able to see that the CLI dies not show the error message for ports. 

image

The error is likely due to the changes made in this [commit](https://github.com/middlewarehq/middleware/pull/451/commits/dcd5c6e626ae8e4a23b9ea0efecb2b05a07b8fe7). Basically, the code was updated to look leaner but the end logic only checks for the promises being settled in `callPortsCheck` and not the values.

image

The below code change should fix the issue.

`      if (checks.some((item) => item.status === 'rejected' || item.value === false)) {`

File: cli/source/hooks/usePreCheck.ts [hunk 7]
```diff
@@ -0,0 +1,84 @@
...
+
+  const callPortsCheck = useCallback(async () => {
+    // For ports
+    const ports_array = [db, redis, frontend, sync_server, analytics_server];
+    if (ports_array.some((port) => isNaN(port))) {
+      setPorts(PreCheckStates.FAILED);
+    } else {
+      const portPromises = ports_array.map(isFreePort);
+      const checks = await Promise.allSettled(portPromises);
+      if (checks.some((item) => item.status === 'rejected')) {
```
[the remark this answers is not in the document]
Comment (samad-yar-khan) [reply cli/source/hooks/usePreCheck.ts:50]: This should fix the bug in the above comment @sidtohan

**Review by samad-yar-khan — CHANGES_REQUESTED** [review]

File: cli/source/hooks/usePreCheck.ts (hunk 7 above)
[the remark this answers is not in the document]
Comment (sidtohan) [reply cli/source/hooks/usePreCheck.ts]: hey @samad-yar-khan , I've made the requested changes. Could you please review it once? Thanks!

**Review by samad-yar-khan — CHANGES_REQUESTED** [review]
@sidtohan  Everything works as expected now! but not able to merge due to conflicts. Can you please rebase the branch ?

**Review by samad-yar-khan — APPROVED** [review]
Amazing work @sidtohan ! Thanks for this contribution 🎉  🚀

**Comment by sidtohan** [comment]
Happy to contribute! 🥳

**Comment by jayantbh** [comment]
Just wanted to drop a comment to appreciate that this was a really solid contribution. 👏🏽 👏🏽 
Definitely avoids certain confusions when running the dev setup. Good stuff, @sidtohan 

In case you're not on our Slack, feel free to join!
https://join.slack.com/t/middle-out-group/shared_invite/zt-2hbuoog3a-k~ojcay1yDJ~a2kVPeEMJg

We'd love to build more things with you.
