### PR TITLE
fix: fixed #397 by adding sorting function to sort on basis of lines changed

### LINKED ISSUE #397: Sorting by lines doesn't work
### Description:

Clicking on the `LINES` header on the PR table doesn't sort correctly

### Steps to reproduce:

1. Go to `/dora-metrics`
2. Click lead-time stats card
3. in the PR table beneath, try sorting by number of lines

### Expected behavior:

- should sort perfectly by number of lines

### Actual behavior:

- sort is broken

### Server Setup Information:

- Operating System: 
- Deployment Method:

### PR DESCRIPTION
**Pull request by KartikChawla09**
Sorting functionality now working as expected

## Linked Issue(s) 
Closes #397 

## Proposed changes (including videos or screenshots)
Sorting on the basis Number of Lines Changed is now working by adding missing sorting functionalities.

## Screenshots
Descending Order (Lines)
image
Ascending Order (Lines)
image

### CODE REVIEW

File: web-server/src/hooks/useTableSort.ts [hunk 1]
```diff
@@ -101,10 +101,44 @@ export const useTableSort = <T = Record<string, any>>(
...
+    return result;
+  }, [conf.order, list, simpleSort]);
+  
+
   const sortedList: T[] = useMemo(() => {
     if (conf.field === 'author') return handleAuthorUsernameSort();
     if (conf.field === 'reviewers') return handleReviewerSort();
     if (conf.field === 'first_response_time') return handleResponseTime();
+    if (conf.field === 'commits') return handleCommitSort();
+    if (conf.field === 'additions') return handleLinesSort();
```
Comment (e-for-eshaan) [inline web-server/src/hooks/useTableSort.ts:141]: since you are utilising `handleLinesSort`, they need to be passed into the dependency array of `sortedList`

File: web-server/src/hooks/useTableSort.ts [hunk 2]
```diff
@@ -101,10 +101,44 @@ export const useTableSort = <T = Record<string, any>>(
...
+      result.sort((a, b) => {
+        return Number(a.commits) - Number(b.commits);
+      });
+    } else {
+      result.sort((b, a) => {
+        return Number(a.commits) - Number(b.commits);
+      });
+    }
+    return result;
+  }, [conf.order, list, simpleSort]);
```
Comment (e-for-eshaan) [inline web-server/src/hooks/useTableSort.ts:117]: Turns out this is not needed, commit sort works fine as is.

**Review by e-for-eshaan — CHANGES_REQUESTED** [review]

File: web-server/src/hooks/useTableSort.ts (hunk 2 above)
Comment (KartikChawla09) [reply web-server/src/hooks/useTableSort.ts:117]: Okay! I will make the necessary changes.

Comment (e-for-eshaan) [reply web-server/src/hooks/useTableSort.ts:117]: Great! Make sure you update the PR description and title (might need to remove commit based snapshots)

Comment (KartikChawla09) [reply web-server/src/hooks/useTableSort.ts]: I have updated the PR description and title, kindly check the latest commit.

**Review by e-for-eshaan — APPROVED** [review]

File: web-server/src/hooks/useTableSort.ts (hunk 2 above)
Comment (e-for-eshaan) [reply web-server/src/hooks/useTableSort.ts]: Great stuff, merging this!
